console.log(`w@wwwwwww@wwwww
w.www@.......@w
w.wwwwwwwwww.ww
@.wwww..wwww@ww
w..@wwwww.ww.ww
www.wwwwwww..@w
ww.....@www.www
ww.ww@...ww@www
ww.ww..@.....@w
@..www@.www@www
w@..wwwwww.wwww
www..@www.wwwww
www.w...@...@..
www.wwwwww@www@
@..@wwwwwwwwwww`)